// This file is auto-generated by @hey-api/openapi-ts

export const $Activity = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    title: {
      type: "string",
      nullable: true,
    },
    dueDate: {
      type: "string",
      format: "date-time",
    },
    completed: {
      type: "boolean",
    },
  },
  additionalProperties: false,
} as const;

export const $Author = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    idBook: {
      type: "integer",
      format: "int32",
    },
    firstName: {
      type: "string",
      nullable: true,
    },
    lastName: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const $Book = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    title: {
      type: "string",
      nullable: true,
    },
    description: {
      type: "string",
      nullable: true,
    },
    pageCount: {
      type: "integer",
      format: "int32",
    },
    excerpt: {
      type: "string",
      nullable: true,
    },
    publishDate: {
      type: "string",
      format: "date-time",
    },
  },
  additionalProperties: false,
} as const;

export const $CoverPhoto = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    idBook: {
      type: "integer",
      format: "int32",
    },
    url: {
      type: "string",
      format: "uri",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const $User = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    userName: {
      type: "string",
      nullable: true,
    },
    password: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;
