// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  GetApiV1ActivitiesError,
  GetApiV1ActivitiesResponse,
  PostApiV1ActivitiesData,
  PostApiV1ActivitiesError,
  PostApiV1ActivitiesResponse,
  GetApiV1ActivitiesByIdData,
  GetApiV1ActivitiesByIdError,
  GetApiV1ActivitiesByIdResponse,
  PutApiV1ActivitiesByIdData,
  PutApiV1ActivitiesByIdError,
  PutApiV1ActivitiesByIdResponse,
  DeleteApiV1ActivitiesByIdData,
  DeleteApiV1ActivitiesByIdError,
  DeleteApiV1ActivitiesByIdResponse,
  GetApiV1AuthorsError,
  GetApiV1AuthorsResponse,
  PostApiV1AuthorsData,
  PostApiV1AuthorsError,
  PostApiV1AuthorsResponse,
  GetApiV1AuthorsAuthorsBooksByIdBookData,
  GetApiV1AuthorsAuthorsBooksByIdBookError,
  GetApiV1AuthorsAuthorsBooksByIdBookResponse,
  GetApiV1AuthorsByIdData,
  GetApiV1AuthorsByIdError,
  GetApiV1AuthorsByIdResponse,
  PutApiV1AuthorsByIdData,
  PutApiV1AuthorsByIdError,
  PutApiV1AuthorsByIdResponse,
  DeleteApiV1AuthorsByIdData,
  DeleteApiV1AuthorsByIdError,
  DeleteApiV1AuthorsByIdResponse,
  GetApiV1BooksError,
  GetApiV1BooksResponse,
  PostApiV1BooksData,
  PostApiV1BooksError,
  PostApiV1BooksResponse,
  GetApiV1BooksByIdData,
  GetApiV1BooksByIdError,
  GetApiV1BooksByIdResponse,
  PutApiV1BooksByIdData,
  PutApiV1BooksByIdError,
  PutApiV1BooksByIdResponse,
  DeleteApiV1BooksByIdData,
  DeleteApiV1BooksByIdError,
  DeleteApiV1BooksByIdResponse,
  GetApiV1CoverPhotosError,
  GetApiV1CoverPhotosResponse,
  PostApiV1CoverPhotosData,
  PostApiV1CoverPhotosError,
  PostApiV1CoverPhotosResponse,
  GetApiV1CoverPhotosBooksCoversByIdBookData,
  GetApiV1CoverPhotosBooksCoversByIdBookError,
  GetApiV1CoverPhotosBooksCoversByIdBookResponse,
  GetApiV1CoverPhotosByIdData,
  GetApiV1CoverPhotosByIdError,
  GetApiV1CoverPhotosByIdResponse,
  PutApiV1CoverPhotosByIdData,
  PutApiV1CoverPhotosByIdError,
  PutApiV1CoverPhotosByIdResponse,
  DeleteApiV1CoverPhotosByIdData,
  DeleteApiV1CoverPhotosByIdError,
  DeleteApiV1CoverPhotosByIdResponse,
  GetApiV1UsersError,
  GetApiV1UsersResponse,
  PostApiV1UsersData,
  PostApiV1UsersError,
  PostApiV1UsersResponse,
  GetApiV1UsersByIdData,
  GetApiV1UsersByIdError,
  GetApiV1UsersByIdResponse,
  PutApiV1UsersByIdData,
  PutApiV1UsersByIdError,
  PutApiV1UsersByIdResponse,
  DeleteApiV1UsersByIdData,
  DeleteApiV1UsersByIdError,
  DeleteApiV1UsersByIdResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export const getApiV1Activities = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1ActivitiesResponse,
    GetApiV1ActivitiesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Activities",
  });
};

export const postApiV1Activities = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1ActivitiesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiV1ActivitiesResponse,
    PostApiV1ActivitiesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Activities",
  });
};

export const getApiV1ActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1ActivitiesByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1ActivitiesByIdResponse,
    GetApiV1ActivitiesByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Activities/{id}",
  });
};

export const putApiV1ActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1ActivitiesByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PutApiV1ActivitiesByIdResponse,
    PutApiV1ActivitiesByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Activities/{id}",
  });
};

export const deleteApiV1ActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1ActivitiesByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteApiV1ActivitiesByIdResponse,
    DeleteApiV1ActivitiesByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Activities/{id}",
  });
};

export const getApiV1Authors = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1AuthorsResponse,
    GetApiV1AuthorsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Authors",
  });
};

export const postApiV1Authors = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1AuthorsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiV1AuthorsResponse,
    PostApiV1AuthorsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Authors",
  });
};

export const getApiV1AuthorsAuthorsBooksByIdBook = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1AuthorsAuthorsBooksByIdBookData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1AuthorsAuthorsBooksByIdBookResponse,
    GetApiV1AuthorsAuthorsBooksByIdBookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Authors/authors/books/{idBook}",
  });
};

export const getApiV1AuthorsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1AuthorsByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1AuthorsByIdResponse,
    GetApiV1AuthorsByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Authors/{id}",
  });
};

export const putApiV1AuthorsById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1AuthorsByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PutApiV1AuthorsByIdResponse,
    PutApiV1AuthorsByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Authors/{id}",
  });
};

export const deleteApiV1AuthorsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1AuthorsByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteApiV1AuthorsByIdResponse,
    DeleteApiV1AuthorsByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Authors/{id}",
  });
};

export const getApiV1Books = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1BooksResponse,
    GetApiV1BooksError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Books",
  });
};

export const postApiV1Books = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1BooksData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiV1BooksResponse,
    PostApiV1BooksError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Books",
  });
};

export const getApiV1BooksById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1BooksByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1BooksByIdResponse,
    GetApiV1BooksByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Books/{id}",
  });
};

export const putApiV1BooksById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1BooksByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PutApiV1BooksByIdResponse,
    PutApiV1BooksByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Books/{id}",
  });
};

export const deleteApiV1BooksById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1BooksByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteApiV1BooksByIdResponse,
    DeleteApiV1BooksByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Books/{id}",
  });
};

export const getApiV1CoverPhotos = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1CoverPhotosResponse,
    GetApiV1CoverPhotosError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/CoverPhotos",
  });
};

export const postApiV1CoverPhotos = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1CoverPhotosData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiV1CoverPhotosResponse,
    PostApiV1CoverPhotosError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/CoverPhotos",
  });
};

export const getApiV1CoverPhotosBooksCoversByIdBook = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1CoverPhotosBooksCoversByIdBookData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1CoverPhotosBooksCoversByIdBookResponse,
    GetApiV1CoverPhotosBooksCoversByIdBookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/CoverPhotos/books/covers/{idBook}",
  });
};

export const getApiV1CoverPhotosById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1CoverPhotosByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1CoverPhotosByIdResponse,
    GetApiV1CoverPhotosByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/CoverPhotos/{id}",
  });
};

export const putApiV1CoverPhotosById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1CoverPhotosByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PutApiV1CoverPhotosByIdResponse,
    PutApiV1CoverPhotosByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/CoverPhotos/{id}",
  });
};

export const deleteApiV1CoverPhotosById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiV1CoverPhotosByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteApiV1CoverPhotosByIdResponse,
    DeleteApiV1CoverPhotosByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/CoverPhotos/{id}",
  });
};

export const getApiV1Users = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1UsersResponse,
    GetApiV1UsersError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Users",
  });
};

export const postApiV1Users = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1UsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiV1UsersResponse,
    PostApiV1UsersError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Users",
  });
};

export const getApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1UsersByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiV1UsersByIdResponse,
    GetApiV1UsersByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Users/{id}",
  });
};

export const putApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1UsersByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PutApiV1UsersByIdResponse,
    PutApiV1UsersByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Users/{id}",
  });
};

export const deleteApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1UsersByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteApiV1UsersByIdResponse,
    DeleteApiV1UsersByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/Users/{id}",
  });
};
