// This file is auto-generated by @hey-api/openapi-ts

export type Activity = {
  id?: number;
  title?: string | null;
  dueDate?: string;
  completed?: boolean;
};

export type Author = {
  id?: number;
  idBook?: number;
  firstName?: string | null;
  lastName?: string | null;
};

export type Book = {
  id?: number;
  title?: string | null;
  description?: string | null;
  pageCount?: number;
  excerpt?: string | null;
  publishDate?: string;
};

export type CoverPhoto = {
  id?: number;
  idBook?: number;
  url?: string | null;
};

export type User = {
  id?: number;
  userName?: string | null;
  password?: string | null;
};

export type GetApiV1ActivitiesResponse = Array<Activity>;

export type GetApiV1ActivitiesError = unknown;

export type PostApiV1ActivitiesData = {
  body?: Activity;
};

export type PostApiV1ActivitiesResponse = Activity;

export type PostApiV1ActivitiesError = unknown;

export type GetApiV1ActivitiesByIdData = {
  path: {
    id: number;
  };
};

export type GetApiV1ActivitiesByIdResponse = Activity;

export type GetApiV1ActivitiesByIdError = unknown;

export type PutApiV1ActivitiesByIdData = {
  body?: Activity;
  path: {
    id: number;
  };
};

export type PutApiV1ActivitiesByIdResponse = Activity;

export type PutApiV1ActivitiesByIdError = unknown;

export type DeleteApiV1ActivitiesByIdData = {
  path: {
    id: number;
  };
};

export type DeleteApiV1ActivitiesByIdResponse = unknown;

export type DeleteApiV1ActivitiesByIdError = unknown;

export type GetApiV1AuthorsResponse = Array<Author>;

export type GetApiV1AuthorsError = unknown;

export type PostApiV1AuthorsData = {
  body?: Author;
};

export type PostApiV1AuthorsResponse = Author;

export type PostApiV1AuthorsError = unknown;

export type GetApiV1AuthorsAuthorsBooksByIdBookData = {
  path: {
    idBook: number;
  };
};

export type GetApiV1AuthorsAuthorsBooksByIdBookResponse = Array<Author>;

export type GetApiV1AuthorsAuthorsBooksByIdBookError = unknown;

export type GetApiV1AuthorsByIdData = {
  path: {
    id: number;
  };
};

export type GetApiV1AuthorsByIdResponse = Author;

export type GetApiV1AuthorsByIdError = unknown;

export type PutApiV1AuthorsByIdData = {
  body?: Author;
  path: {
    id: number;
  };
};

export type PutApiV1AuthorsByIdResponse = Author;

export type PutApiV1AuthorsByIdError = unknown;

export type DeleteApiV1AuthorsByIdData = {
  path: {
    id: number;
  };
};

export type DeleteApiV1AuthorsByIdResponse = unknown;

export type DeleteApiV1AuthorsByIdError = unknown;

export type GetApiV1BooksResponse = Array<Book>;

export type GetApiV1BooksError = unknown;

export type PostApiV1BooksData = {
  body?: Book;
};

export type PostApiV1BooksResponse = unknown;

export type PostApiV1BooksError = unknown;

export type GetApiV1BooksByIdData = {
  path: {
    id: number;
  };
};

export type GetApiV1BooksByIdResponse = Book;

export type GetApiV1BooksByIdError = unknown;

export type PutApiV1BooksByIdData = {
  body?: Book;
  path: {
    id: number;
  };
};

export type PutApiV1BooksByIdResponse = unknown;

export type PutApiV1BooksByIdError = unknown;

export type DeleteApiV1BooksByIdData = {
  path: {
    id: number;
  };
};

export type DeleteApiV1BooksByIdResponse = unknown;

export type DeleteApiV1BooksByIdError = unknown;

export type GetApiV1CoverPhotosResponse = Array<CoverPhoto>;

export type GetApiV1CoverPhotosError = unknown;

export type PostApiV1CoverPhotosData = {
  body?: CoverPhoto;
};

export type PostApiV1CoverPhotosResponse = CoverPhoto;

export type PostApiV1CoverPhotosError = unknown;

export type GetApiV1CoverPhotosBooksCoversByIdBookData = {
  path: {
    idBook: number;
  };
};

export type GetApiV1CoverPhotosBooksCoversByIdBookResponse = Array<CoverPhoto>;

export type GetApiV1CoverPhotosBooksCoversByIdBookError = unknown;

export type GetApiV1CoverPhotosByIdData = {
  path: {
    id: number;
  };
};

export type GetApiV1CoverPhotosByIdResponse = CoverPhoto;

export type GetApiV1CoverPhotosByIdError = unknown;

export type PutApiV1CoverPhotosByIdData = {
  body?: CoverPhoto;
  path: {
    id: number;
  };
};

export type PutApiV1CoverPhotosByIdResponse = CoverPhoto;

export type PutApiV1CoverPhotosByIdError = unknown;

export type DeleteApiV1CoverPhotosByIdData = {
  path: {
    id: number;
  };
};

export type DeleteApiV1CoverPhotosByIdResponse = unknown;

export type DeleteApiV1CoverPhotosByIdError = unknown;

export type GetApiV1UsersResponse = Array<User>;

export type GetApiV1UsersError = unknown;

export type PostApiV1UsersData = {
  body?: User;
};

export type PostApiV1UsersResponse = unknown;

export type PostApiV1UsersError = unknown;

export type GetApiV1UsersByIdData = {
  path: {
    id: number;
  };
};

export type GetApiV1UsersByIdResponse = unknown;

export type GetApiV1UsersByIdError = unknown;

export type PutApiV1UsersByIdData = {
  body?: User;
  path: {
    id: number;
  };
};

export type PutApiV1UsersByIdResponse = unknown;

export type PutApiV1UsersByIdError = unknown;

export type DeleteApiV1UsersByIdData = {
  path: {
    id: number;
  };
};

export type DeleteApiV1UsersByIdResponse = unknown;

export type DeleteApiV1UsersByIdError = unknown;
